# Generated by Django 5.1.6 on 2025-05-30 05:39

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Description of the banner')),
                ('banner_image', cloudinary.models.CloudinaryField(help_text='Banner image stored in Cloudinary', max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the banner was created')),
            ],
        ),
    ]
