# Generated by Django 5.1.6 on 2025-05-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('percentage', 'Percentage')], default='flat', max_length=20),
        ),
    ]
