# Generated by Django 5.1.6 on 2025-05-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_coupon_coupon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
