# Generated by Django 5.1.6 on 2025-05-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_coupon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
