# Generated by Django 5.1.6 on 2025-05-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
