# Generated by Django 5.1.6 on 2025-04-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
    ]
