# Generated by Django 5.1.6 on 2025-05-09 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0003_referral'),
        ('offer', '0004_coupon_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='coupon',
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_coupons', to='offer.coupon'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer_coupons', to='offer.coupon'),
        ),
    ]
