# Generated by Django 5.1.6 on 2025-02-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gold_weight',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
