# Generated by Django 5.1.6 on 2025-03-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0002_product_productvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='price',
            new_name='gold_price',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gold_color',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='making_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stone_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
