# Generated by Django 5.1.6 on 2025-03-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0003_rename_price_productvariant_gold_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gold_color',
            field=models.CharField(default='yellow', max_length=50),
        ),
    ]
