# Generated by Django 5.1.6 on 2025-03-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_alter_product_gold_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gold_color',
            field=models.CharField(default='yellow', max_length=100),
        ),
    ]
