# Generated by Django 5.1.6 on 2025-03-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0005_alter_product_gold_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
