# Generated by Django 5.1.6 on 2025-03-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0007_alter_product_name_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='imag'),
        ),
    ]
