# Generated by Django 5.1.6 on 2025-03-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0008_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='gross_weight',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
