# Generated by Django 5.1.6 on 2025-04-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0010_alter_productimage_image_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
