# Generated by Django 5.1.6 on 2025-04-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0012_alter_category_name_category_unique_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='category',
            name='category_offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='category',
            name='category_offer_Isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer_Isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
