# Generated by Django 5.1.6 on 2025-04-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0013_remove_product_discount_category_category_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=10),
        ),
    ]
