# Generated by Django 5.1.6 on 2025-04-06 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0003_address_isdefault'),
        ('cartapp', '0002_order_orderaddress_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticationapp.address'),
        ),
    ]
