# Generated by Django 5.1.6 on 2025-05-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
