# Generated by Django 5.1.6 on 2025-05-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_orderitem_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_image_url',
            new_name='product_image',
        ),
    ]
