# Generated by Django 5.1.6 on 2025-05-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0004_rename_product_image_url_orderitem_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('return_denied', 'Return Denied')], default='active', max_length=20),
        ),
    ]
