# Generated by Django 5.1.6 on 2025-05-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0004_remove_cart_tax_cart_final_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_tax',
            field=models.DecimalField(db_default=0.0, decimal_places=2, max_digits=10),
        ),
    ]
