# Generated by Django 5.1.6 on 2025-04-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0004_rename_total_amount_order_total_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=False, max_length=20, unique=True),
        ),
    ]
