# Generated by Django 5.1.6 on 2025-05-02 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0005_order_total_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cartapp.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='est_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
