# Generated by Django 5.1.6 on 2025-04-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0006_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='est_delivery',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
