# Generated by Django 5.1.6 on 2025-04-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0007_order_est_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_amount',
        ),
    ]
