# Generated by Django 5.1.6 on 2025-05-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0007_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.CharField(default='null', max_length=20, unique=True),
        ),
    ]
