# Generated by Django 5.1.6 on 2025-05-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0008_wallettransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
