# Generated by Django 5.1.6 on 2025-04-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0008_rename_total_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='active', max_length=20),
        ),
    ]
