# Generated by Django 5.1.6 on 2025-04-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0012_remove_wallettransaction_timestamp_wallet_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('return_requested', 'Return Requested')], default='active', max_length=20),
        ),
    ]
