# Generated by Django 5.1.6 on 2025-05-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0012_orderitem_tax_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
