# Generated by Django 5.1.6 on 2025-05-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0013_order_coupon_discount_orderitem_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested')], default='active', max_length=20),
        ),
    ]
