# Generated by Django 5.1.6 on 2025-04-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0013_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
