# Generated by Django 5.1.6 on 2025-05-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0014_orderitem_payment_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
