# Generated by Django 5.1.6 on 2025-05-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0016_cart_coupon_cart_final_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
