# Generated by Django 5.1.6 on 2025-04-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
