# Generated by Django 5.1.6 on 2025-04-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0018_order_approve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='approve',
            new_name='approve_status',
        ),
    ]
