# Generated by Django 5.1.6 on 2025-04-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0019_rename_approve_order_approve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
