# Generated by Django 5.1.6 on 2025-04-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0021_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
